version: '3'
services:
  ### Primary container with Cicada
  cicada_dev:
    image: python:3.8-buster
    # image: python:3.10-buster
    container_name: cicada_dev
    working_dir: ${CICADA_HOME}
    entrypoint: ${CICADA_HOME}/local-dev/entrypoint.sh
    environment:
      CICADA_HOME: ${CICADA_HOME}
      DB_POSTGRES_HOST: cicada_db
      DB_POSTGRES_PORT: ${DB_POSTGRES_PORT}
      DB_POSTGRES_PORT_ON_HOST: ${DB_POSTGRES_PORT_ON_HOST}
      DB_POSTGRES_USER: ${DB_POSTGRES_USER}
      DB_POSTGRES_PASS: ${DB_POSTGRES_PASS}
      DB_POSTGRES_DB: ${DB_POSTGRES_DB}

    volumes:
      - ../:${CICADA_HOME}
    depends_on:
      - cicada_db
    networks:
      - cicada_network

  # PostgreSQL database container used as backend
  cicada_db:
    image: debezium/postgres:12-alpine
    container_name: cicada_db
    ports:
      - ${DB_POSTGRES_PORT_ON_HOST}:${DB_POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASS}
      POSTGRES_DB: ${DB_POSTGRES_DB}
    networks:
      - cicada_network

networks:
  cicada_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.52.0/24
