db_cicada:
    host: db_cicada
    port: 5432
    dbname: db_cicada
    user: cicada
    password: randomstring

slack:
    token: xyz48945
    channel: channel_name
    returncodes_alert: *   # Its default value is *, it can also be a list of error codes i.e [1, 13, -1]

