name: Build
on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: [ self-hosted, production ]
    container: docker.tw.ee/actions_sonar4

    steps:
      - uses: actions/checkout@v2
      - name: Run SonarQube Analysis
        shell: bash
        run: >
          sonar-scanner
          -Dsonar.projectKey=transferwise_cicada
          -Dsonar.projectName=transferwise_cicada
          -Dsonar.host.url=$SONAR_HOST_URL
          -Dsonar.login=$SONAR_TOKEN
          -Dsonar.sources=./
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
